apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: {{ .Values.vote.app }}
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: {{ .Values.vote.service.port }}
    targetPort: {{ .Values.vote.service.targetport }}
  selector:
    app: {{ .Values.vote.app }}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.result.app }}
  name: result
spec:
  type: LoadBalancer
  ports:
  - name: "result-service"
    port: {{ .Values.result.service.port }}
    targetPort: {{ .Values.result.service.targetport }}
  selector:
    app: result

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
  selector:
    app: db

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  type: ClusterIP
  ports:
  - name: "redis-service"
    port: 6379
    targetPort: 6379
  selector:
    app: redis




